# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
[package]
name = "icu"
description = "International Components for Unicode"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "Cargo.toml",
    "README.md"
]

[dependencies]
icu_datetime = { version = "0.1", path = "../datetime" }
icu_locid = { version = "0.1", path = "../locid" }
icu_locid_macros = { version = "0.1", path = "../locid/macros" }
icu_plurals = { version = "0.1", path = "../plurals" }
icu_uniset = { version = "0.1", path = "../uniset" }

[dev-dependencies]
icu_testdata = { version = "0.1", path = "../../resources/testdata" }
